import numpy as np
import argparse
import os

P = argparse.ArgumentParser()
P.add_argument('-f', default='pomerol_eigenvalues.dat', help="An data file of eigenvalues generated by pomerol")
args = P.parse_args()
# print args

file=args.f

def analyze_line(_line):
    # Input: something like  _line="-6  [1,0.5]"
    # Return: [energy, n_tot]

    if _line[0] == '#':  # skip comment line
        return None, None

    array=_line.split()
    # print array
    energy=float(array[0])

    quantum_numbers = array[1][1:-1].split(',')  # remove '[' and ']', and split by ','
    # print quantum_numbers

    return energy, int(quantum_numbers[0])


# set the following variables by reading eigenvalues in a file
E0=None
N0=None
E_plus=None
E_minus=None

with open(file, "r") as f:
    for line in f:
        e, n = analyze_line(line)
        # print e, n
        if e is None:  # skip comment line
            continue
        if E0 is None:
            E0=e
            N0=n
            # print E0, N0
        else:
            if E_plus is None and n == N0+1:
                E_plus = e - E0
            if E_minus is None and n == N0-1:
                E_minus = e - E0
            # break if both E_plus and E_minus have been set
            if E_plus is not None and E_minus is not None:
                break

print("# generated by '%s'" %os.path.basename(__file__))
print("# from eigenvalues in '%s'" %file)
print("[SCL]")
print("E_plus =", E_plus)
print("E_minus =", E_minus)
