name: deploy

on:
  push:
    branches:
      - main
      - develop
      - gh_actions  # test branch
      - '**-autodoc'
      - '!gh-pages'
    tags: '*'

jobs:
  deploy:
    runs-on: ubuntu-24.04
    environment: "deploy_docs"
    steps:
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v3.x

    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: main

    - name: Checkout gh-pages
      uses: actions/checkout@v4
      with:
        ref: gh-pages
        path: gh-pages

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx wild_sphinx_theme

    - name: Build
      run: |
        cd ${GITHUB_WORKSPACE}/main/
        sphinx-build -b html ./doc ./built_doc

    - name: Deploy Configuration
      run: |
          mkdir ~/.ssh
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
          echo "${{ secrets.GH_ACTIONS_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 400 ~/.ssh/id_ed25519

    - name: Push
      env:
        GIT_USER: "ChiQ Developers"
        GIT_EMAIL: "bse-dev@issp.u-tokyo.ac.jp"
        REF_SLUG: ${{ env.GITHUB_REF_SLUG }}
      run: |
          cd ${GITHUB_WORKSPACE}
          feature_branch=${REF_SLUG%-autodoc}
          if [ "_${REF_SLUG}" != "_${feature_branch}" ]; then
            TARGET_NAME=${feature_branch}
          else
            TARGET_NAME=${REF_SLUG}
          fi
          rm -rf "gh-pages/manual/${TARGET_NAME}"
          cp -r "main/built_doc" "gh-pages/manual/${TARGET_NAME}/html"
          cd gh-pages
          git config --local user.name "${GIT_USER}"
          git config --local user.email "${GIT_EMAIL}"
          git remote set-url origin git@github.com:${GITHUB_REPOSITORY}.git
          git pull
          git add ${TARGET_NAME}
          if git commit -m "Deploy docs to ${TARGET_NAME} by GitHub Actions triggered by ${GITHUB_SHA}"
          then
            git push origin gh-pages
          else
            echo "Nothing to deploy"
          fi
